setup warnings set -connectType1 InPort -connectType2 InPort -severity error
setup warnings set -connectType1 InPort -connectType2 OutPort -severity warning
setup warnings set -connectType1 InPort -connectType2 InOutPort -severity warning
setup warnings set -connectType1 InPort -connectType2 OtherPort -severity warning
setup warnings set -connectType1 InPort -connectType2 InPin -severity ignore
setup warnings set -connectType1 InPort -connectType2 OutPin -severity error
setup warnings set -connectType1 InPort -connectType2 InOutPin -severity ignore
setup warnings set -connectType1 InPort -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 InPort -connectType2 NoConnection -severity warning
setup warnings set -connectType1 OutPort -connectType2 OutPort -severity error
setup warnings set -connectType1 OutPort -connectType2 InOutPort -severity warning
setup warnings set -connectType1 OutPort -connectType2 OtherPort -severity warning
setup warnings set -connectType1 OutPort -connectType2 InPin -severity ignore
setup warnings set -connectType1 OutPort -connectType2 OutPin -severity ignore
setup warnings set -connectType1 OutPort -connectType2 InOutPin -severity ignore
setup warnings set -connectType1 OutPort -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 OutPort -connectType2 NoConnection -severity warning
setup warnings set -connectType1 InOutPort -connectType2 InOutPort -severity ignore
setup warnings set -connectType1 InOutPort -connectType2 OtherPort -severity warning
setup warnings set -connectType1 InOutPort -connectType2 InPin -severity ignore
setup warnings set -connectType1 InOutPort -connectType2 OutPin -severity ignore
setup warnings set -connectType1 InOutPort -connectType2 InOutPin -severity ignore
setup warnings set -connectType1 InOutPort -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 InOutPort -connectType2 NoConnection -severity warning
setup warnings set -connectType1 OtherPort -connectType2 OtherPort -severity ignore
setup warnings set -connectType1 OtherPort -connectType2 InPin -severity ignore
setup warnings set -connectType1 OtherPort -connectType2 OutPin -severity ignore
setup warnings set -connectType1 OtherPort -connectType2 InOutPin -severity ignore
setup warnings set -connectType1 OtherPort -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 OtherPort -connectType2 NoConnection -severity warning
setup warnings set -connectType1 InPin -connectType2 InPin -severity ignore
setup warnings set -connectType1 InPin -connectType2 OutPin -severity ignore
setup warnings set -connectType1 InPin -connectType2 InOutPin -severity ignore
setup warnings set -connectType1 InPin -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 InPin -connectType2 NoConnection -severity warning
setup warnings set -connectType1 OutPin -connectType2 OutPin -severity error
setup warnings set -connectType1 OutPin -connectType2 InOutPin -severity ignore
setup warnings set -connectType1 OutPin -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 OutPin -connectType2 NoConnection -severity warning
setup warnings set -connectType1 InOutPin -connectType2 InOutPin -severity ignore
setup warnings set -connectType1 InOutPin -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 InOutPin -connectType2 NoConnection -severity ignore
setup warnings set -connectType1 OtherPin -connectType2 OtherPin -severity ignore
setup warnings set -connectType1 OtherPin -connectType2 NoConnection -severity ignore