setup warnings set -check InstanceNames -severity warning
setup warnings set -check ScriptValidatedNames -severity warning
setup warnings set -check ScriptValidatedViewNames -severity warning
setup warnings set -check ScriptValidatedNetLabels -severity warning
setup warnings set -check ScriptValidatedPorts -severity warning
setup warnings set -check UserScriptValidatedView -severity warning
setup warnings set -check ScriptValidatedCellNames -severity warning
setup warnings set -check SymbolPortsExistOnSchematic -severity warning
setup warnings set -check SchematicPortsExistOnSymbol -severity warning
setup warnings set -check PortConsistencyAcrossViews -severity warning
setup warnings set -check SymbolPropertyConsistency -severity warning
setup warnings set -check UserScriptValidatedCell -severity warning
setup warnings set -check Names -severity warning
setup warnings set -check CellNameInMultipleLibraries -severity warning
setup warnings set -check Pinorder -severity warning
setup warnings set -check OverlappingInstances -severity warning
setup warnings set -check OverlappingPins -severity warning
setup warnings set -check NetLabelAtWireCrossingPoint -severity warning
setup warnings set -check DanglingPins -severity warning
setup warnings set -check DanglingNamedWires -severity ignore
setup warnings set -check DanglingWires -severity warning
setup warnings set -check DanglingPortsOrNetLabels -severity warning
setup warnings set -check OverlappingWires -severity warning
setup warnings set -check 4-WayCrossingWireConnection -severity warning
setup warnings set -check OverlappingNetLabelAndPin -severity warning
setup warnings set -check LonelyNets -severity warning
setup warnings set -check BusesNamedInAscendingOrder -severity ignore
setup warnings set -check BusesNamedInDescendingOrder -severity ignore
setup warnings set -check ShortedNets -severity error
setup warnings set -check NetNameDifferentFromPortName -severity warning
setup warnings set -check IllegalConnection -severity error
setup warnings set -check UndrivenNets -severity warning
setup warnings set -check ConnectivityCompatibility -severity error
setup warnings set -check VerilogNameSpace -severity warning
setup warnings set -check VerilogReservedName -severity warning
setup warnings set -check VerilogQuotedName -severity warning
setup warnings set -check VerilogModuleNameMismatch -severity warning
setup warnings set -check VhdlReservedName -severity warning
setup warnings set -check VhdlQuotedName -severity warning
setup warnings set -check VhdlSignalInstanceNameSpace -severity warning
setup warnings set -check VhdlCellInstanceNameSpace -severity warning
setup warnings set -check VhdlPortMapping -severity ignore
setup warnings set -check SpiceInstanceNameCollision -severity warning
setup warnings set -check SpiceCellNameCollision -severity warning
setup warnings set -check SpiceNetNameCollision -severity warning
setup warnings set -check SpiceSubcktNameMismatch -severity warning
setup warnings set -check OpenAccessTrialSave -severity warning
setup warnings set -check NetCaps -severity warning
setup warnings set -check Undefined -severity error
setup warnings set -check Undefined -severity warning